name: Docker push for CEG3120

# do this on the main branch
on:
  push:
    branches:
      - main

jobs:
  docker-upload:
    runs-on: ubuntu-latest

    #checkout the code
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

    #login to docker
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      #build docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fischbach-ceg3120:latest